FROM nvidia/cuda:12.2.2-cudnn8-devel-ubuntu22.04
# BUILD FROM NVIDIA CUDA DEV IMAGE, CHOOSE THE CORRECT VERSION THEN INSTALL CONDA (Need to restart, therefore commit first)
LABEL authors="Xuanli"

ENTRYPOINT ["top", "-b"]

